config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'profiles/index'
  resources :likes, only: [:create, :destroy]
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get 'home/about'

  resources :users, only: [:show]
  resources :posts do
    resources :comments
  end
  post 'users/:id/follow', to: "users#follow", as: "follow"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow"
  post 'users/:id/accept', to: "users#accept", as: "accept"
  post 'users/:id/decline', to: "users#decline", as: "decline"
  post 'users/:id/cancel', to: "users#cancel", as: "cancel"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "posts#index"
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: {minimum: 5, maximum: 100}
    validates :description, presence: true, length: {minimum: 5, maximum: 500}
    validates :keywords, presence: true, length: {minimum: 5, maximum: 100}

    has_many_attached :images
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_noticed_notifications model_name: 'Notification'
    has_many :notifications, through: :user, dependent: :destroy

    has_many :likes
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  include Pagy::Backend
  # GET /posts or /posts.json
  def index
    @posts = Post.order(:created_at => :desc)
    @pagy, @posts = pagy(@posts, items: 1)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.order(created_at: :desc)
    mark_notifications_as_read
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.likes.destroy_all
    @post.destroy
    


    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :user_id,  :keywords, images: [])
    end

    def mark_notifications_as_read
      if current_user
        notifications_to_mark_as_read = @post.notifications_as_post.where(recipient: current_user)
        notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="col-xl-4 col-md-6 col-sm8 col-10" style="margin: auto; background-color: #FDE8B6; padding: 20px;">
<%= form_with(model: post) do |form| %>
<h1>New post</h1>
  <div>
    <% invalid = post.errors.include?(:title) %>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title, class: "form-control" %>
    <% if invalid %>
    <p style="color: red">
      <%= post.errors.full_messages_for(:title).join(" ,") %></p>
    <% end %>
    </div>

    <div>
      <%= form.text_field :user_id, type: "hidden", value: current_user.id %>
    
    </div>
    
    <div>
      <% invalid = post.errors.include?(:description) %>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_field :description, class: "form-control" %>
      <% if invalid %>
    <p style="color: red">
      <%= post.errors.full_messages_for(:description).join(" ,") %></p>
    <% end %>
    </div>

    <div>
      <% invalid = post.errors.include?(:keywords) %>
      <%= form.label :keywords, style: "display: block" %>
      <%= form.text_field :keywords, class: "form-control" %>
      <% if invalid %>
    <p style="color: red">
      <%= post.errors.full_messages_for(:keywords).join(" ,") %></p>
    <% end %>
    </div> <br>
    
      <%= form.file_field :images, multiple:true %><br><hr/>

    <div>
      <%= form.submit class: "btn btn-primary col-12" %>
    </div> <br>
  
<% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="post-container text-center">
  <p>
    <strong><%= post.title %></strong>
  </p>

  <p>
    <%= post.description %>
  </p>

  <p>
      <%= link_to "", post, class:"post-link" %>
  </p>
  <% post.images.each do |image| %>
    <%= image_tag(image, style: "object-fit: cover; width: 300px; height: 600px;") %>
  <% end %>
  <p>
    <strong>Keywords:</strong>
    <%= post.keywords %>
  </p>
</div>
<div class="container text-center">
  <p><%= pluralize(post.likes.count, "like") %></p>
  
  <% if user_signed_in? %>
  <% like = current_user.likes.find_by(post: post) %>
  <% if like.nil? %>
    <%= button_to "Like", likes_path, params: {like: { post_id: post.id }}, method: :post %>
  <% else %>
    <%= button_to "Unlike", like_path(like),  method: :delete %>
  <% end %>
  <% end %>
  
  <p>
    <h6>Posted by </h6><%= link_to post.user.email, post.user %>
  </p>
</div><br>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<%= stylesheet_link_tag("post") %>
<p style="color: green"><%= notice %></p>
<div id="posts" class="text-center">
  
  <% if user_signed_in? %>
  <% if current_user.admin? %>
    You are an Admin
  <% end %>
  <div class="container mt-4">
    <div class="row">
      <div class="col-md-6">
        <h2>Follow Requests</h2>
        <ul class="list-group">
          <% current_user.follow_requests.each do |request| %>
            <li class="list-group-item">
              <%= request.followerable.email %> Wants to follow you
              <%= button_to "Accept", accept_path(request.followerable), method: :post, class: "btn btn-primary btn-sm ml-2" %>
              <%= button_to "Decline", decline_path(request.followerable), method: :post, class: "btn btn-danger btn-sm ml-2" %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="col-md-6">
        <h2>Followers</h2>
        <ul class="list-group">
          <% current_user.followers.each do |follower| %>
            <li class="list-group-item">
              <%= link_to follower.email, follower %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    
    <div class="mt-4">
      <h2>Following</h2>
      <ul class="list-group">
        <% current_user.following.each do |following| %>
          <li class="list-group-item">
            <%= link_to following.email, following %>
          </li>
        <% end %>
      </ul>
    </div>
  </div><br>
<% end %>

  <%= link_to "New post", new_post_path, class: "btn btn-primary"%>
  <%= raw pagy_bootstrap_nav(@pagy) %>
   <% @posts.each do |post| %>
  <% if user_signed_in? %>
    <% if current_user.following?(post.user) || post.user == current_user %>
      <%= render post %>
    <% end %>
  <% else %>
    <%= render post %>
  <% end %>
<% end %>

</div>

app/views/posts/new.html.erb
<div class="row">
  <%= render "form", post: @post %>
</div>

<br>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "Back to posts", posts_path, class: "btn btn-primary" %>
<%= render @post %>
<% if user_signed_in? %>
  <% if current_user.id == @post.user.id%>
    <div class="container text-center">
      <%= link_to "Edit this post", edit_post_path(@post), class: "btn btn-warning" %> 
      <%= button_to "Destroy this post", @post, method: :delete, class: "btn btn-danger" %>
    </div> <br>
  <% end %>
<% end %>

<div class="container">
  <%= render 'comments/form', post: @post, comment: @post.comments.build, submit_label: "Reply"  %>
  <% @comments.each do |comment| %>
    <%= render 'comments/comment', post: @post, comment: comment %>
  <% end %>
</div>